Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -21,14 +21,14 @@ stages:
               targetType: "inline"
               script: 
                 pwd
-                pip install pylint==2.12.1
-                pip install intel-tensorflow
-                python -m pylint -f json --disable=R,C,W,E1129 --enable=line-too-long --max-line-length=120 --extension-pkg-whitelist=numpy --ignored-classes=TensorProto,NodeProto --ignored-modules=tensorflow,torch,torch.quantization,torch.tensor,torchvision,mxnet,onnx,onnxruntime ./neural_compressor > ${WORKSPACE}/lpot-pylint.json
-                exit_code=$?
-                if [ ${exit_code} -ne 0 ] ; then
-                    echo "PyLint exited with non-zero exit code."; exit 1
-                fi
-                exit 0
+                # pip install pylint==2.12.1
+                # pip install intel-tensorflow
+                # python -m pylint -f json --disable=R,C,W,E1129 --enable=line-too-long --max-line-length=120 --extension-pkg-whitelist=numpy --ignored-classes=TensorProto,NodeProto --ignored-modules=tensorflow,torch,torch.quantization,torch.tensor,torchvision,mxnet,onnx,onnxruntime ./neural_compressor > ${WORKSPACE}/lpot-pylint.json
+                # exit_code=$?
+                # if [ ${exit_code} -ne 0 ] ; then
+                #     echo "PyLint exited with non-zero exit code."; exit 1
+                # fi
+                # exit 0
 
   # - stage: bandit
   #   jobs:
