Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -9,7 +9,6 @@ pr:
 pool: wenjiao-test
 
 variables:
-  # WORKSPACE: $(pwd)
   VAL_PATH: /home2/wenjiaoy/sxh/val/frameworks.ai.lpot.lpot-validation
   target_path: "neural_compressor"
 
@@ -32,23 +31,22 @@ stages:
 #                 fi
 #                 exit 0
 
-  - stage: bandit
-    dependsOn: []
-    jobs:
-      - job: bandit_test
-        steps:
-          - task: Bash@3
-            inputs:
-              targetType: "inline"
-              script: |
-                $(Build.SourcesDirectory)
-                pip install bandit
-                python -m bandit -r -lll -iii neural_compressor >  $(Build.SourcesDirectory)/lpot-bandit.log
-                exit_code=$?
-                if [ ${exit_code} -ne 0 ] ; then
-                  echo "Bandit exited with non-zero exit code."; exit 1
-                fi
-                  exit 0
+  # - stage: bandit
+  #   dependsOn: []
+  #   jobs:
+  #     - job: bandit_test
+  #       steps:
+  #         - task: Bash@3
+  #           inputs:
+  #             targetType: "inline"
+  #             script: |
+  #               pip install bandit
+  #               python -m bandit -r -lll -iii neural_compressor >  $(Build.SourcesDirectory)/lpot-bandit.log
+  #               exit_code=$?
+  #               if [ ${exit_code} -ne 0 ] ; then
+  #                 echo "Bandit exited with non-zero exit code."; exit 1
+  #               fi
+                  # exit 0
 
 #   - stage: pyspelling
 #     dependsOn: []
@@ -71,66 +69,70 @@ stages:
 #                 sed -i "s|\${LPOT_REPO}|$(WORKSPACE)|g" $(VAL_PATH)/neural_coder/pyspelling_conf.yaml
 #                 echo "Modified config:"
 #                 cat $(VAL_PATH)/neural_coder/pyspelling_conf.yaml
-#                 pyspelling -c $(VAL_PATH)/neural_coder/pyspelling_conf.yaml > $(WORKSPACE)/pyspelling_output.log
+#                 pyspelling -c $(VAL_PATH)/neural_coder/pyspelling_conf.yaml > $(Build.SourcesDirectory)/pyspelling_output.log
 #                 exit_code=$?
 #                 if [ ${exit_code} -ne 0 ] ; then
 #                     echo "Pyspelling exited with non-zero exit code."; exit 1
 #                 fi
 #                 exit 0
 
-  # - stage: copyright
-  #   dependsOn: []
-  #   jobs:
-  #     - job: copyright_check
-  #       steps:
-  #         - task: Bash@3
-  #           inputs:
-  #             targetType: "inline"
-  #             script: |
-  #               supported_extensions=(py, sh, yaml)
-  #               echo "tf diff ---- start ------" 
-  #               tf diff
-  #               echo "tf diff ---- end -------"
-  #               MR_target_branch="license-test"
-  #               # -----------------  ??????   params, MR_target_branch    ????????  ---------------
-  #               # if ['supported_extensions' in params && params.supported_extensions != ''] ; then
-  #               #     supported_extensions = params.supported_extensions
-  #               # fi
-  #               echo  ${supported_extensions}
+  - stage: copyright
+    dependsOn: []
+    jobs:
+      - job: copyright_check
+        steps:
+          - task: Bash@3
+            inputs:
+              targetType: "inline"
+              script: |
+                echo "---------------- pullRequest ------------------"
+                $(System.PullRequest.SourceBranch)
+                $(System.PullRequest.TargetBranch)
+                echo "---------------- pullRequest ------------------"
+                supported_extensions=(py, sh, yaml)
+                echo "tf diff ---- start ------" 
+                tf diff
+                echo "tf diff ---- end -------"
+                MR_target_branch="license-test"
+                # -----------------  ??????   params, MR_target_branch    ????????  ---------------
+                # if ['supported_extensions' in params && params.supported_extensions != ''] ; then
+                #     supported_extensions = params.supported_extensions
+                # fi
+                echo  ${supported_extensions}
 
                 
               
-  #               set -xe
-  #               # supported_extensions=($(echo "$(extensions)" | tr "," " ")) 
-  #               git --no-pager diff --name-only $(git show-ref -s remotes/origin/${MR_target_branch}) ./$(target_path) > $(WORKSPACE)/diff.log
-  #               cat $(WORKSPACE)/diff.log
-  #               files=$(cat $(WORKSPACE)/diff.log | awk '!a[$0]++')
+                set -xe
+                # supported_extensions=($(echo "$(extensions)" | tr "," " ")) 
+                git --no-pager diff --name-only $(git show-ref -s remotes/origin/${MR_target_branch}) ./$(target_path) > $(WORKSPACE)/diff.log
+                cat $(WORKSPACE)/diff.log
+                files=$(cat $(WORKSPACE)/diff.log | awk '!a[$0]++')
 
-  #               for file in ${files}
-  #               do
-  #                   echo "hello world 1"
-  #                   if [[ "${supported_extensions[@]}" =~ "${file##*.}" ]]; then
-  #                       echo "hello world 2"
-  #                       echo "Checking license in ${file}"
+                for file in ${files}
+                do
+                    echo "hello world 1"
+                    if [[ "${supported_extensions[@]}" =~ "${file##*.}" ]]; then
+                        echo "hello world 2"
+                        echo "Checking license in ${file}"
                         
-  #                       if [ $(grep -E -c "Copyright \\(c\\) ([0-9]{4})(-[0-9]{4})? Intel Corporation" ${file}) = 0 ]; then
-  #                           echo "hello world 3"
-  #                           echo ${files} >> $(WORKSPACE)/copyright_issue_summary.log
-  #                       fi
-  #                   else
-  #                       echo "Skipping ${file}"
-  #                   fi
-  #               done
-  #     - job: status_check
-  #       dependsOn: copyright_check
-  #       steps:
-  #         - task: Bash@3
-  #           inputs:
-  #             targetType: "inline"
-  #             script: |
-  #               ls $(WORKSPACE)/copyright_issue_summary.log
-  #               exit_code=$?
-  #               if [ ${exit_code} -ne 0 ] ; then
-  #                   echo "------------------Check <copyright_issue_summary.log> for wrong file list !!!!!!!!!!!!!!!!!!!!!!!"; exit 1
-  #               fi
-  #               exit 0
+                        if [ $(grep -E -c "Copyright \\(c\\) ([0-9]{4})(-[0-9]{4})? Intel Corporation" ${file}) = 0 ]; then
+                            echo "hello world 3"
+                            echo ${files} >> $(Build.SourcesDirectory)/copyright_issue_summary.log
+                        fi
+                    else
+                        echo "Skipping ${file}"
+                    fi
+                done
+      - job: status_check
+        dependsOn: copyright_check
+        steps:
+          - task: Bash@3
+            inputs:
+              targetType: "inline"
+              script: |
+                ls $(Build.SourcesDirectory)/copyright_issue_summary.log
+                exit_code=$?
+                if [ ${exit_code} -ne 0 ] ; then
+                    echo "------------------Check <copyright_issue_summary.log> for wrong file list !!!!!!!!!!!!!!!!!!!!!!!"; exit 1
+                fi
+                exit 0
