Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -12,23 +12,23 @@ variables:
   WORKSPACE: $(pwd)
 
 stages:
-  - stage: pylint
-    jobs:
-      - job: pylint_test
-        steps:
-          - task: Bash@3
-            inputs:
-              targetType: "inline"
-              script: |
-                # python -m pylint -f json --disable=R,C,W,E1129 --enable=line-too-long --max-line-length=120 --extension-pkg-whitelist=numpy --ignored-classes=TensorProto,NodeProto --ignored-modules=tensorflow,torch,torch.quantization,torch.tensor,torchvision,mxnet,onnx,onnxruntime ./neural_compressor > /home2/wenjiaoy/publicAzure/_work/9/s/lpot-pylint.json
-                pip install pylint==2.12.1
-                pip install intel-tensorflow
-                python -m pylint -f json --disable=R,C,W,E1129 --enable=line-too-long --max-line-length=120 --extension-pkg-whitelist=numpy --ignored-classes=TensorProto,NodeProto --ignored-modules=tensorflow,torch,torch.quantization,torch.tensor,torchvision,mxnet,onnx,onnxruntime ./neural_compressor #> $(WORKSPACE)/lpot-pylint.json
-                exit_code=$?
-                if [ ${exit_code} -ne 0 ] ; then
-                    echo "PyLint exited with non-zero exit code."; exit 1
-                fi
-                exit 0
+  # - stage: pylint
+  #   jobs:
+  #     - job: pylint_test
+  #       steps:
+  #         - task: Bash@3
+  #           inputs:
+  #             targetType: "inline"
+  #             script: |
+  #               # python -m pylint -f json --disable=R,C,W,E1129 --enable=line-too-long --max-line-length=120 --extension-pkg-whitelist=numpy --ignored-classes=TensorProto,NodeProto --ignored-modules=tensorflow,torch,torch.quantization,torch.tensor,torchvision,mxnet,onnx,onnxruntime ./neural_compressor > /home2/wenjiaoy/publicAzure/_work/9/s/lpot-pylint.json
+  #               pip install pylint==2.12.1
+  #               pip install intel-tensorflow
+  #               python -m pylint -f json --disable=R,C,W,E1129 --enable=line-too-long --max-line-length=120 --extension-pkg-whitelist=numpy --ignored-classes=TensorProto,NodeProto --ignored-modules=tensorflow,torch,torch.quantization,torch.tensor,torchvision,mxnet,onnx,onnxruntime ./neural_compressor > $(WORKSPACE)/lpot-pylint.json
+  #               exit_code=$?
+  #               if [ ${exit_code} -ne 0 ] ; then
+  #                   echo "PyLint exited with non-zero exit code."; exit 1
+  #               fi
+  #               exit 0
 
   # - stage: bandit
   #   jobs:
@@ -58,11 +58,12 @@ stages:
                 # Update paths to validation and lpot repositories
                 VAL_REPO=${WORKSPACE}
 
-                sed -i "s|\${VAL_REPO}|$VAL_REPO|g" ${VAL_REPO}/pyspelling_conf.yaml
-                sed -i "s|\${LPOT_REPO}|$REPO_DIR|g" ${VAL_REPO}/pyspelling_conf.yaml
+                # sed -i "s|\${VAL_REPO}|$VAL_REPO|g" ${VAL_REPO}/pyspelling_conf.yaml
+                # sed -i "s|\${LPOT_REPO}|$REPO_DIR|g" ${VAL_REPO}/pyspelling_conf.yaml
+                sed -i "s|\${VAL_REPO}|$VAL_REPO|g" $(WORKSPACE)/pyspelling_conf.yaml
                 echo "Modified config:"
-                cat ${VAL_REPO}/pyspelling_conf.yaml
-                pyspelling -c ${VAL_REPO}/pyspelling_conf.yaml > ${WORKSPACE}/pyspelling_output.log
+                cat $$(WORKSPACE)/pyspelling_conf.yaml
+                pyspelling -c $$(WORKSPACE)/pyspelling_conf.yaml > $(WORKSPACE)/pyspelling_output.log
                 exit_code=$?
                 if [ ${exit_code} -ne 0 ] ; then
                     echo "Pyspelling exited with non-zero exit code."; exit 1
