Set up CI with Azure Pipelines
[skip ci]

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,36 +1,67 @@
-# Python package
-# Create and test a Python package on multiple Python versions.
-# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
-# https://docs.microsoft.com/azure/devops/pipelines/languages/python
+# Starter pipeline
+# Start with a minimal pipeline that you can customize to build and deploy your code.
+# Add steps that build, run tests, deploy, and more:
+# https://aka.ms/yaml
 
-trigger:
-- master
+pr:
+  - main
 
-pool:
-  vmImage: ubuntu-latest
-strategy:
-  matrix:
-    Python27:
-      python.version: '2.7'
-    Python35:
-      python.version: '3.5'
-    Python36:
-      python.version: '3.6'
-    Python37:
-      python.version: '3.7'
+pool: wenjiao-test
 
-steps:
-- task: UsePythonVersion@0
-  inputs:
-    versionSpec: '$(python.version)'
-  displayName: 'Use Python $(python.version)'
+stages:
+  - stage: pylint
+    jobs:
+      - job: pylint_test
+        steps:
+          - task: Bash@3
+            inputs:
+              targetType: "inline"
+              script: |
+                pwd
+                pip install pylint==2.12.1
+                pip install intel-tensorflow
+                python -m pylint -f json --disable=R,C,W,E1129 --enable=line-too-long --max-line-length=120 --extension-pkg-whitelist=numpy --ignored-classes=TensorProto,NodeProto --ignored-modules=tensorflow,torch,torch.quantization,torch.tensor,torchvision,mxnet,onnx,onnxruntime ./neural_compressor > /lpot-pylint.json
+                # # exit_code=$?
+                # # if [ ${exit_code} -ne 0 ] ; then
+                # #     echo "PyLint exited with non-zero exit code."; exit 1
+                # # fi
+                # # exit 0
 
-- script: |
-    python -m pip install --upgrade pip
-    pip install -r requirements.txt
-  displayName: 'Install dependencies'
+  - stage: bandit
+    jobs:
+      - job: bandit_test
+        steps:
+          - task: Bash@3
+            inputs:
+              targetType: "inline"
+#               script: |
+#                 pip install bandit
+#                 # python -m bandit -r -lll -iii neural_compressor > ${WORKSPACE}/lpot-bandit.log
+#                 # exit_code=$?
+#                 # if [ ${exit_code} -ne 0 ] ; then
+#                 #     echo "Bandit exited with non-zero exit code."; exit 1
+#                 # fi
+#                 # exit 0
 
-- script: |
-    pip install pytest pytest-azurepipelines
-    pytest
-  displayName: 'pytest'
+  # - stage: pyspelling
+  #   jobs:
+  #     - job: pyspelling_test
+#         steps:
+#           - task: Bash@3
+#             inputs:
+#               targetType: "inline"
+#               script: |
+#                 pip install pyspelling
+#                 # Update paths to validation and lpot repositories
+#                 # VAL_REPO=${WORKSPACE}
+
+#                 # sed -i "s|\${VAL_REPO}|$VAL_REPO|g" ${VAL_REPO}/pyspelling_conf.yaml
+#                 # sed -i "s|\${LPOT_REPO}|$REPO_DIR|g" ${VAL_REPO}/pyspelling_conf.yaml
+#                 # echo "Modified config:"
+#                 # cat ${VAL_REPO}/pyspelling_conf.yaml
+#                 # pyspelling -c ${VAL_REPO}/pyspelling_conf.yaml > ${WORKSPACE}/pyspelling_output.log
+#                 # exit_code=$?
+#                 # if [ ${exit_code} -ne 0 ] ; then
+#                 #     echo "Pyspelling exited with non-zero exit code."; exit 1
+#                 # fi
+#                 # exit 0
