Optimize model template (#123)

diff --git a/.azure-pipelines/template/model-template.yml b/.azure-pipelines/template/model-template.yml
--- a/.azure-pipelines/template/model-template.yml
+++ b/.azure-pipelines/template/model-template.yml
@@ -1,14 +1,14 @@
 parameters:
-- name: modelName
-  type: string
-  default: 'resnet50v1.5'
-- name: framework
-  type: string
-  default: 'tensorflow'
+  - name: modelName
+    type: string
+    default: "resnet50v1.5"
+  - name: framework
+    type: string
+    default: "tensorflow"
 
-- name: modelContainerName
-  type: string
-  default: 'model'
+  - name: modelContainerName
+    type: string
+    default: "model"
 
 steps:
   - template: docker-template.yml
@@ -28,4 +28,11 @@ steps:
     inputs:
       targetPath: $(Build.SourcesDirectory)/.azure-pipelines/scripts/models/${{ parameters.modelName }}/
       artifact: ${{ parameters.framework }}_${{ parameters.modelName }}
-      publishLocation: 'pipeline'
+      publishLocation: "pipeline"
+
+  - script: |
+      if [ ${{ parameters.framework }}_${{ parameters.modelName }}_failed == 'true' ]; then
+        echo "[Failed] Model ${{ parameters.modelName }} failed, please check artifacts and logs."
+        exit 1
+      fi
+    displayName: "Check Test Status"
