Code scan optimization (#28)

diff --git a/.azure-pipelines/code-scan.yml b/.azure-pipelines/code-scan.yml
--- a/.azure-pipelines/code-scan.yml
+++ b/.azure-pipelines/code-scan.yml
@@ -5,11 +5,12 @@ pr:
 pool: suyue-test
 
 variables:
-  IMAGE_NAME: "neural-compressor"
-  IMAGE_TAG: "py38"
+  IMAGE_NAME: "code-scan"
+  IMAGE_TAG: "1.0"
   CODE_SCAN_PATH: ".azure-pipelines/scripts/codeScan"
   CODE_SCAN_LOG_PATH: ".azure-pipelines/scripts/codeScan/scanLog"
   CURRENT_PATH: $(Build.SourcesDirectory)
+
 
 stages:
   - stage: BanditCodeScan
@@ -27,8 +28,8 @@ stages:
           - checkout: self
             displayName: "Checkout out Repo"
           - script: |
-              if [[ ! $(docker images | grep -i ${IMAGE_NAME}) ]]; then
-                  docker build -f ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/docker/Dockerfile.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
+              if [[ ! $(docker images | grep -i '${IMAGE_NAME}:${IMAGE_TAG}' ) ]]; then
+                  docker build -f ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/docker/DockerfileCodeScan.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
               fi
               docker images | grep -i ${IMAGE_NAME}
               if [[ $? -ne 0 ]]; then
@@ -40,15 +41,12 @@ stages:
               docker stop $(docker ps -aq)
               docker rm -vf $(docker ps -aq) || true
             displayName: "Clean Docker"
-
           - task: Bash@3
             inputs:
               targetType: "inline"
               script: |
                 docker run --disable-content-trust --privileged --name="bandit" -v ${BUILD_SOURCESDIRECTORY}:/neural-compressor ${IMAGE_NAME}:${IMAGE_TAG} bash /neural-compressor/$(CODE_SCAN_PATH)/bandit/bandit.sh
-                
             displayName: "Bandit Check"
-
           - task: PublishPipelineArtifact@1
             condition: always()
             inputs:
@@ -73,8 +71,8 @@ stages:
           - checkout: self
             displayName: "Checkout out Repo"
           - script: |
-              if [[ ! $(docker images | grep -i ${IMAGE_NAME}) ]]; then
-                  docker build -f ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/docker/Dockerfile.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
+              if [[ ! $(docker images | grep -i '${IMAGE_NAME}:${IMAGE_TAG}' ) ]]; then
+                  docker build -f ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/docker/DockerfileCodeScan.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
               fi
               docker images | grep -i ${IMAGE_NAME}
               if [[ $? -ne 0 ]]; then
@@ -86,21 +84,19 @@ stages:
               docker stop $(docker ps -aq)
               docker rm -vf $(docker ps -aq) || true
             displayName: "Clean Docker"
-
           - task: Bash@3
             inputs:
               targetType: "inline"
               script: |
                 docker run --disable-content-trust --privileged --name="pylint" -v ${BUILD_SOURCESDIRECTORY}:/neural-compressor ${IMAGE_NAME}:${IMAGE_TAG} bash /neural-compressor/$(CODE_SCAN_PATH)/pylint/pylint.sh
             displayName: "Pylint Check"
-
           - task: PublishPipelineArtifact@1
             condition: always()
             inputs:
               targetPath: $(CURRENT_PATH)/$(CODE_SCAN_LOG_PATH)/lpot-pylint.json
               artifact: pylint
               publishLocation: "pipeline"
-            displayName: "Status Check"
+            displayName: "PublishPipelineArtifact"
 
 
   - stage: PyspellingCodeScan
@@ -118,8 +114,8 @@ stages:
           - checkout: self
             displayName: "Checkout out Repo"
           - script: |
-              if [[ ! $(docker images | grep -i ${IMAGE_NAME}) ]]; then
-                  docker build -f ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/docker/Dockerfile.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
+              if [[ ! $(docker images | grep -i '${IMAGE_NAME}:${IMAGE_TAG}' ) ]]; then
+                  docker build -f ${BUILD_SOURCESDIRECTORY}/.azure-pipelines/docker/DockerfileCodeScan.devel -t ${IMAGE_NAME}:${IMAGE_TAG} .
               fi
               docker images | grep -i ${IMAGE_NAME}
               if [[ $? -ne 0 ]]; then
@@ -131,14 +127,12 @@ stages:
               docker stop $(docker ps -aq)
               docker rm -vf $(docker ps -aq) || true
             displayName: "Clean Docker"
-
           - task: Bash@3
             inputs:
               targetType: "inline"
               script: |
                 docker run --disable-content-trust --privileged --name="pyspelling" -v ${BUILD_SOURCESDIRECTORY}:/neural-compressor ${IMAGE_NAME}:${IMAGE_TAG} bash /neural-compressor/$(CODE_SCAN_PATH)/pyspelling/pyspelling.sh
             displayName: "Pyspelling Check"
-
           - task: PublishPipelineArtifact@1
             condition: always()
             inputs:
@@ -146,6 +140,7 @@ stages:
               artifact: pyspelling
               publishLocation: "pipeline"   
             displayName: "PublishPipelineArtifact"
+
 
   - stage: CopyRight
     displayName: CopyRight Code Scan
@@ -164,8 +159,10 @@ stages:
             inputs:
               targetType: "inline"
               script: |
-                set -xe
-                mkdir -p $(CURRENT_PATH)/$(CODE_SCAN_LOG_PATH)
+                source $(CURRENT_PATH)/.azure-pipelines/scripts/change_color.sh
+                set -e
+                mkdir -p $(CURRENT_PATH)/$(CODE_SCAN_LOG_PATH)            
+                RESET="echo -en \\E[0m \\n"  # close 
 
                 supported_extensions=(py, sh, yaml)
                 git --no-pager diff --name-only $(git show-ref -s remotes/origin/$(System.PullRequest.TargetBranch)) $(CURRENT_PATH)/neural_compressor > $(CURRENT_PATH)/$(CODE_SCAN_LOG_PATH)/diff.log
@@ -174,17 +171,18 @@ stages:
                 for file in ${files}
                 do
                     if [[ "${supported_extensions[@]}" =~ "${file##*.}" ]]; then
-                        echo "Checking license in 1 ${file}"
                         if [ $(grep -E -c "Copyright \\(c\\) ([0-9]{4})(-[0-9]{4})? Intel Corporation" ${file}) = 0 ]; then
                             echo ${file} >>  $(CURRENT_PATH)/$(CODE_SCAN_LOG_PATH)/copyright_issue_summary.log
-                            echo "------------------Check <copyright_issue_summary.log> for wrong file list !!!!!!!!!!!!!!!!!!!!!!!"; exit 1
+                            $BOLD_YELLOW && echo " -----------------  Current log file output start --------------------------"
+                            cat   $(CURRENT_PATH)/$(CODE_SCAN_LOG_PATH)/copyright_issue_summary.log
+                            $BOLD_YELLOW && echo " -----------------  Current log file output end --------------------------" && $RESET
+                            $BOLD_RED && echo "CopyRight has something wrong! Please click on the artifact button to download and view the error log!" && $RESET; exit 1
                         fi
                     else
-                        echo "Skipping ${file}"
+                        $LIGHT_PURPLE && echo "Skipping ${file}"  && $RESET
                     fi
                 done
             displayName: "CopyRight Check"
-
           - task: PublishPipelineArtifact@1
             condition: failed()
             inputs:
