test model generate

diff --git a/.azure-pipelines/model-test.yml b/.azure-pipelines/model-test.yml
--- a/.azure-pipelines/model-test.yml
+++ b/.azure-pipelines/model-test.yml
@@ -198,42 +198,42 @@ stages:
               artifact:
               patterns: '**/*_tuning_info.log'
               path: $(OUT_SCRIPT_PATH)
-          # - task: UsePythonVersion@0
-          #   displayName: 'Use Python 3.'
+          - task: UsePythonVersion@0
+            displayName: 'Use Python 3.'
+            inputs:
+              versionSpec: '3'
+          # - script: |
+          #     cd ${OUT_SCRIPT_PATH}
+          #     mkdir generated
+          #     mkdir last_generated
+          #     python -u collect_log_all.py --logs_dir $(OUT_SCRIPT_PATH) --output_dir generated
+          #   displayName: "Collect all logs"
+          # - task: DownloadPipelineArtifact@2
           #   inputs:
-          #     versionSpec: '3'
-          - script: |
-              cd ${OUT_SCRIPT_PATH}
-              mkdir generated
-              mkdir last_generated
-              python -u collect_log_all.py --logs_dir $(OUT_SCRIPT_PATH) --output_dir generated
-            displayName: "Collect all logs"
-          - task: DownloadPipelineArtifact@2
-            inputs:
-              source: 'specific'
-              artifact: 'FinalReport'
-              patterns: '**.log'
-              path: $(OUT_SCRIPT_PATH)/last_generated
-              project: $(System.TeamProject)
-              pipeline: 'Baseline'
-              runVersion: 'specific'
-              runId: $(model_runID)
-              retryDownloadCount: 3
-            displayName: 'Download last logs'
-          - script: |
-              echo "------ Generating final report.html ------"
-              cd ${OUT_SCRIPT_PATH}
-              /usr/bin/bash generate_report.sh --WORKSPACE generated --output_dir generated --last_logt_dir last_generated
-            displayName: 'Generate report'
-          - task: PublishPipelineArtifact@1
-            inputs:
-              targetPath: $(OUT_SCRIPT_PATH)/generated
-              artifact: FinalReport
-              publishLocation: 'pipeline'
-            displayName: "Publish report"
-          - script: |
-              if [ $(is_perf_reg) == 'true' ]; then
-                echo "[Performance Regression] Some model performance regression occurred, please check artifacts and reports."
-                exit 1
-              fi
-            displayName: "Specify performance regression"
+          #     source: 'specific'
+          #     artifact: 'FinalReport'
+          #     patterns: '**.log'
+          #     path: $(OUT_SCRIPT_PATH)/last_generated
+          #     project: $(System.TeamProject)
+          #     pipeline: 'Baseline'
+          #     runVersion: 'specific'
+          #     runId: $(model_runID)
+          #     retryDownloadCount: 3
+          #   displayName: 'Download last logs'
+          # - script: |
+          #     echo "------ Generating final report.html ------"
+          #     cd ${OUT_SCRIPT_PATH}
+          #     /usr/bin/bash generate_report.sh --WORKSPACE generated --output_dir generated --last_logt_dir last_generated
+          #   displayName: 'Generate report'
+          # - task: PublishPipelineArtifact@1
+          #   inputs:
+          #     targetPath: $(OUT_SCRIPT_PATH)/generated
+          #     artifact: FinalReport
+          #     publishLocation: 'pipeline'
+          #   displayName: "Publish report"
+          # - script: |
+          #     if [ $(is_perf_reg) == 'true' ]; then
+          #       echo "[Performance Regression] Some model performance regression occurred, please check artifacts and reports."
+          #       exit 1
+          #     fi
+          #   displayName: "Specify performance regression"
