sync azure-pipeline with public repo

diff --git a/.azure-pipelines/model-test.yml b/.azure-pipelines/model-test.yml
--- a/.azure-pipelines/model-test.yml
+++ b/.azure-pipelines/model-test.yml
@@ -228,20 +228,20 @@ stages:
               fi
             displayName: "Check Test Status"
 
-      - job: bert_base_MRPC_static
-        displayName: bert_base_MRPC_static
-        steps:
-          - template: template/model-template.yml
-            parameters:
-              modelName: 'bert_base_MRPC_static'
-              framework: 'onnxrt'
-               
-          - script: |
-              if [ $(onnxrt_bert_base_MRPC_static_failed) == 'true' ]; then
-                echo "[Failed] Model bert_base_MRPC_static failed, please check artifacts and logs."
-                exit 1
-              fi
-            displayName: "Check Test Status"
+#      - job: distilbert_base_MRPC_qdq
+#        displayName: distilbert_base_MRPC_qdq
+#        steps:
+#          - template: template/model-template.yml
+#            parameters:
+#              modelName: 'distilbert_base_MRPC_qdq'
+#              framework: 'onnxrt'
+#
+#          - script: |
+#              if [ $(onnxrt_distilbert_base_MRPC_qdq_failed) == 'true' ]; then
+#                echo "[Failed] Model distilbert_base_MRPC_qdq failed, please check artifacts and logs."
+#                exit 1
+#              fi
+#            displayName: "Check Test Status"
 
       - job: bert_base_MRPC_dynamic
         displayName: bert_base_MRPC_dynamic
@@ -289,7 +289,6 @@ stages:
             inputs:
               versionSpec: '3.8.0'
           - script: |
-              echo "------ Collecting logs ------"
               cd ${OUT_SCRIPT_PATH}
               mkdir generated
               mkdir last_generated
@@ -301,8 +300,8 @@ stages:
               artifact: 'FinalReport'
               patterns: '**.log'
               path: $(OUT_SCRIPT_PATH)/last_generated
-              project: 'test-lpot-public'
-              pipeline: 45
+              project: $(System.TeamProject)
+              pipeline: 'Baseline'
               runVersion: 'specific'
               runId: $(model_runID)
               retryDownloadCount: 3
@@ -324,7 +323,3 @@ stages:
                 exit 1
               fi
             displayName: "Specify performance regression"
-
-
-
-
